# Generated by Django 4.2.3 on 2023-10-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.TextField(choices=[('like', 'Like'), ('heart', 'Heart')], default='like', max_length=9)),
                ('likedBy', models.ManyToManyField(to='core.profile')),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
    ]
