# Generated by Django 4.2.3 on 2023-10-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likedPost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
