# Generated by Django 4.2.3 on 2023-10-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_post'),
        ('friends', '0002_alter_friendrequest_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='core.profile'),
        ),
    ]
